name: Refine Configs (Stage 2 - GitHub)

on:
  schedule:
    # This runs every 2 hours. You can change the schedule if you want.
    - cron: '15 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 45

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run GitHub Refining Script
        # This ENV variable tells main.py to run in "GitHub Mode"
        env:
          RUN_MODE: GITHUB
        run: python main.py

      - name: Commit and push Stage 2 list
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📦 Stage 2: Refined list from GitHub"
          # This tells the action to only add the specific file we want
          file_pattern: github-refined-list.txt
