name: Refine V2Ray Configs

on:
  schedule:
    # Runs at 1:00, 5:00, 9:00, 13:00, 17:00, 21:00 UTC
    - cron: '0 1-23/4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 180

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Note: Using v5, which is latest
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Refined & Specially Categorized Configs"
