# FILE: .github/workflows/runner.yml (for your SECOND repo: v2ray-refiner)

name: Refine V2Ray Configs (Hourly)

on:
  schedule:
    # UPDATED: This now runs at the top of every hour (minute 0).
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 45 # Reduced timeout as it runs more frequently

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Refined & Specially Categorized Configs"
